# Vietnamese strings for /vi/ — same keys as S / JS / TERMS in build.py.

S = {
 'about_p4': 'Thuê xe ô tô ở Nha Trang ở đâu? Bạn có thể đặt qua các trang tổng hợp, cửa hàng cho thuê gần biển hoặc thuê trực tiếp từ chủ xe. VietAvto cho thuê xe trực tiếp tại Nha Trang: không phí trung gian, ảnh thật của từng xe, trả lời qua WhatsApp hoặc Telegram. Giao xe tại khách sạn hoặc sân bay Cam Ranh.',
 'q9': 'Thuê xe tự lái ở Nha Trang ở đâu?',
 'a9': 'Ngay tại đây: chọn xe và ngày ở mẫu phía trên — bạn thuê trực tiếp từ chủ xe, không qua trung gian. Giao xe tại khách sạn, địa chỉ ở Nha Trang hoặc sân bay Cam Ranh.',
 'q10': 'Có thể thuê xe không cần cọc không?',
 'a10': 'Cần đặt cọc: $200 cho chuyến đi trong tỉnh Khánh Hòa và $400 cho toàn Việt Nam. Tiền cọc được hoàn lại nếu xe không hư hại và không có phạt.',
 'about_p3': 'Tìm nơi thuê xe tự lái giá rẻ ở Nha Trang? Lựa chọn tiết kiệm nhất là xe điện VinFast VF3 giá 700.000 ₫/ngày và sedan Kia Soluto giá 900.000 ₫. Thuê từ một tháng trở lên có giá riêng, ưu đãi hơn. Gia đình và nhóm bạn có thể chọn Toyota Rush, Veloz, Mitsubishi Xpander 7 chỗ, nhóm đông hơn chọn Kia Carnival 7–11 chỗ.',
 'q7': 'Giá thuê xe tự lái ở Nha Trang bao nhiêu?',
 'a7': 'Từ 700.000 ₫/ngày với VinFast VF3 đến 2.100.000 ₫ với Kia Carnival. Sedan từ 900.000 ₫, xe 7 chỗ từ 1.000.000 ₫. Giá ghi trên từng xe ở trên.',
 'q8': 'Thuê xe theo tháng có rẻ hơn không?',
 'a8': 'Có. Thuê từ một tháng, giá mỗi ngày thấp hơn đáng kể — gửi ngày và mẫu xe qua mẫu đặt xe hoặc WhatsApp/Telegram, chúng tôi sẽ báo giá.',
 'title': 'Thuê xe tự lái Nha Trang — giá từ 700.000 ₫/ngày | VietAvto',
 'meta_desc': 'Cho thuê xe tự lái tại Nha Trang: VinFast, Toyota, Mitsubishi, Hyundai, Kia. Giá từ 700.000 ₫/ngày, cọc từ $200, giao xe tại khách sạn hoặc sân bay Cam Ranh. Đặt xe online, trả lời qua WhatsApp và Telegram.',
 'meta_kw': 'thuê xe tự lái Nha Trang, cho thuê xe ô tô Nha Trang, thuê xe tự lái sân bay Cam Ranh, thuê xe VinFast Nha Trang, thuê xe 7 chỗ Nha Trang, giá thuê xe tự lái Nha Trang',
 'og_locale': 'vi_VN',
 'about_h': 'Thuê xe tự lái tại Nha Trang',
 'about_p1': 'Thuê xe tự lái ở Nha Trang là cách thuận tiện nhất để khám phá bờ biển Khánh Hòa theo lịch của riêng bạn: bãi biển, đảo, thác nước và đèo lên Đà Lạt. VietAvto cho thuê xe từ đội xe riêng — từ xe điện VinFast VF3, VF5 đến Toyota Veloz, Mitsubishi Xpander 7 chỗ và MPV Kia Carnival.',
 'about_p2': 'Giá thuê xe tự lái tại Nha Trang từ 700.000 ₫/ngày, tiền cọc $200 trong tỉnh và $400 khi đi khắp Việt Nam. Giao xe tại khách sạn, địa chỉ ở Nha Trang hoặc sân bay Cam Ranh (CXR). Cần hộ chiếu, giấy phép lái xe quốc tế và bằng lái quốc gia.',
 'nav_fleet': 'Đội xe', 'nav_terms': 'Điều kiện', 'nav_faq': 'Hỏi đáp', 'nav_contact': 'Liên hệ',
 'nav_book': 'Đặt xe',
 'pill': 'Đội xe riêng tại Nha Trang',
 'h1': 'Thuê xe tự lái tại Nha Trang',
 'lede': 'Xe thật từ đội xe của chúng tôi — từ xe điện VinFast nhỏ gọn đến MPV 7 chỗ. Không qua trung gian, tiền cọc rõ ràng, trả xe cùng mức xăng.',
 'perk1': '10+ xe<br>sẵn sàng',
 'perk2': 'Không qua<br>trung gian',
 'perk3': 'Trả lời qua WhatsApp<br>hoặc Telegram',
 'f_car': 'Xe', 'f_car_any': 'Bất kỳ — tư vấn giúp tôi',
 'f_from': 'Ngày nhận xe', 'f_to': 'Ngày trả xe',
 'b_send': 'Gửi yêu cầu',
 'f_contact': 'WhatsApp hoặc Telegram của bạn',
 'f_contact_ph': '+84 912 345 678 hoặc @username',
 'f_name': 'Tên của bạn', 'f_name_ph': 'Chúng tôi nên gọi bạn là gì',
 'f_place': 'Nơi nhận xe (không bắt buộc)',
 'f_place_ph': 'Khách sạn, địa chỉ hoặc sân bay Cam Ranh',
 'or_chat': 'hoặc nhắn cho chúng tôi:',
 'book_hint': '«Gửi yêu cầu» — chúng tôi sẽ nhắn cho bạn. WhatsApp và Telegram mở cuộc trò chuyện với nội dung đã điền sẵn.',
 'fleet_h': 'Đội xe',
 'fleet_p': 'Giá theo ngày, xe tự lái (không kèm tài xế). Thuê từ một tháng trở lên có giá riêng — hỏi khi đặt xe.',
 'per_day': '/ ngày',
 'ft1_h': 'Xe thật', 'ft1_p': 'Ảnh là xe trong đội xe của chúng tôi, không phải ảnh mạng.',
 'ft2_h': 'Điều kiện rõ ràng', 'ft2_p': 'Tiền cọc, số km và xăng đều ghi rõ bên dưới — không có chữ nhỏ.',
 'ft3_h': 'Giao xe tại Nha Trang', 'ft3_p': 'Hẹn địa điểm thuận tiện — khách sạn, địa chỉ hoặc sân bay.',
 'ft4_h': 'Liên hệ trực tiếp', 'ft4_p': 'Nhắn trực tiếp cho chủ xe qua WhatsApp hoặc Telegram — không qua tổng đài.',
 'terms_h': 'Điều kiện thuê xe',
 'road_k': 'Khi lái xe',
 'road_v': 'Tuân thủ luật giao thông<small>Chỉ đỗ xe ở nơi được phép, không vượt đèn đỏ, không chạy quá tốc độ và không lái xe khi đã uống rượu bia. Phạt nguội từ camera gửi về chủ xe và được trừ vào tiền cọc.</small>',
 'faq_h': 'Hỏi đáp',
 'q1': 'Có cần bằng lái quốc tế không?',
 'a1': 'Có. Để ký hợp đồng cần hộ chiếu, giấy phép lái xe quốc tế (IDP) và bằng lái xe quốc gia của bạn.',
 'q2': 'Tiền cọc là bao nhiêu?',
 'a2': '$200 cho chuyến đi trong tỉnh Khánh Hòa và $400 cho toàn Việt Nam. Tiền cọc được hoàn lại nếu xe không bị hư hại và không có phạt; nếu có sẽ trừ tương ứng.',
 'q3': 'Có thể đi Đà Lạt hoặc xa hơn không?',
 'a3': 'Được, với tiền cọc $400. Giới hạn 250 km mỗi ngày và được cộng dồn cho cả thời gian thuê: 3 ngày = 750 km. Mỗi km vượt giới hạn là 5.000 ₫.',
 'q4': 'Nhận xe ở đâu?',
 'a4': 'Địa điểm giao xe được thống nhất khi đặt: khách sạn, địa chỉ ở Nha Trang hoặc sân bay Cam Ranh.',
 'q5': 'Đặt xe như thế nào?',
 'a5': 'Chọn xe và ngày ở mẫu phía trên rồi bấm «Gửi yêu cầu» — chúng tôi sẽ nhắn cho bạn. Hoặc nhắn trực tiếp qua WhatsApp hay Telegram.',
 'q6': 'Nhận và trả xe lúc mấy giờ?',
 'a6': 'Thuê 1 ngày — nhận xe từ 7:00, trả trước 22:00 cùng ngày. Thuê từ 2 ngày — trả xe trước 22:00 ngày cuối cùng.',
 'cta_h': 'Sẵn sàng lên đường?',
 'cta_p': 'Gửi mẫu xe và ngày — chúng tôi chọn xe còn sẵn và hẹn gặp tại Nha Trang.',
 'cta_book': 'Gửi yêu cầu', 'cta_wa': 'Nhắn qua WhatsApp', 'cta_tg': 'Nhắn qua Telegram',
 'footer_l': 'Cho thuê xe tự lái · Nha Trang, Việt Nam',
 'footer_r': '18+ · Chỉ cho thuê xe tự lái',
 'lb_close': 'Đóng', 'lb_prev': 'Ảnh trước', 'lb_next': 'Ảnh sau',
}

JS = {
 'seats': 'chỗ', 'gb_auto': 'Số tự động', 'gb_manual': 'Số sàn',
 'fu_petrol': 'Xăng', 'fu_electric': 'Điện', 'fu_diesel': 'Dầu', 'fu_hybrid': 'Hybrid',
 'per_day': '/ ngày', 'per_day_short': '/ngày', 'book': 'Đặt xe',
 'approx': 'khoảng',
 'disc_from': 'từ 5 ngày',
 'rate_month': 'giá theo tháng',
 'rate_3m': 'giá 3–6 tháng',
 'month_from': 'tháng',
 'per_month': '/tháng',
 'month_hint': '· từ 30 ngày — giá theo tháng, rẻ hơn',
 'disc_applied': 'giảm giá từ 5 ngày',
 'disc_hint': '· từ 5 ngày −50.000 ₫/ngày',
 'no_photo': 'Ảnh sắp có',
 'err_from': 'Vui lòng chọn ngày nhận xe.',
 'err_to': 'Vui lòng chọn ngày trả xe.',
 'err_order': 'Ngày trả xe phải sau ngày nhận xe.',
 'err_contact': 'Vui lòng nhập số WhatsApp hoặc Telegram (@username) để chúng tôi trả lời.',
 'err_send': 'Không gửi được yêu cầu. Vui lòng nhắn cho chúng tôi qua WhatsApp hoặc Telegram bằng các nút bên dưới.',
 'send': 'Gửi yêu cầu', 'sending': 'Đang gửi…',
 'ok_prefix': 'Đã gửi yêu cầu! Chúng tôi sẽ liên hệ với bạn sớm qua: ',
 'tg_copied': 'Nếu nội dung chưa hiện trong Telegram — đã được sao chép, bạn chỉ cần dán và gửi.',
 'via_form': 'Заявка с сайта',
 'm_hello': 'Xin chào! Tôi muốn thuê xe.',
 'm_car': 'Xe: ', 'm_any': 'bất kỳ, nhờ tư vấn giúp',
 'm_dates': 'Ngày: ', 'm_price': 'Giá trên web: ', 'm_total': 'tổng ≈ ',
 'm_place': 'Nơi nhận xe: ', 'm_name': 'Tên: ', 'm_contact': 'Liên hệ của tôi: ',
}

# Same order as build.TERMS
TERMS = [
 ('Giảm giá từ 5 ngày', '−50.000 ₫ mỗi ngày<small>Thuê từ 5 ngày trở lên, mỗi ngày rẻ hơn 50.000 ₫: ví dụ 900.000 ₫ → 850.000 ₫.</small>'),
 ('Số km', '250 km mỗi ngày<small>Giới hạn được cộng dồn cho cả thời gian thuê: 3 ngày = 750 km. Mỗi km vượt giới hạn là 5.000 ₫.</small>'),
 ('Giờ nhận và trả xe', '1 ngày: 7:00 — 22:00<small>Thuê từ 2 ngày — trả xe trước 22:00 ngày cuối cùng.</small>'),
 ('Tiền cọc — Khánh Hòa', '$200<small>Nha Trang và khu vực lân cận. Hoàn lại khi trả xe không hư hại.</small>'),
 ('Tiền cọc — toàn Việt Nam', '$400<small>Hoàn $200 khi trả xe, $200 còn lại sau một tháng — phạt nguội từ camera có thể đến muộn.</small>'),
 ('Giấy tờ', 'Hộ chiếu + IDP + bằng lái quốc gia<small>Cần để ký hợp đồng thuê xe.</small>'),
 ('Thanh toán', 'Sau khi kiểm tra xe<small>Bạn thanh toán sau khi ký hợp đồng và kiểm tra thân xe, nội thất.</small>'),
 ('Xăng', 'Cùng mức xăng<small>Trả xe với mức xăng như lúc nhận. Nếu ít hơn — bạn trả phần chênh lệch.</small>'),
 ('Rửa xe', '350.000 ₫<small>Nếu xe trả về bị bẩn, chúng tôi rửa với phí này.</small>'),
 ('Hư hại và phạt', 'Trừ vào tiền cọc<small>Khi xe bị hư hại hoặc có phạt vi phạm giao thông, tiền cọc sẽ bị trừ tương ứng.</small>'),
 ('Thuê theo tháng', 'Từ 15.000.000 ₫ mỗi tháng<small>Giá tháng ghi trên từng xe, từ 3 tháng còn rẻ hơn. Mẫu đặt xe tự tính giá.</small>'),
]

# Car class/description translations, keyed by car id (used to seed cars.json cls_vi/desc_vi).
CARS = {
 'vf3': ('Ô tô điện mini', 'Xe điện đô thị do Việt Nam sản xuất: đi được khoảng 210 km mỗi lần sạc, dài chỉ 3,2 m — đỗ được ở những chỗ sedan không vừa. Lý tưởng để đi lại trong Nha Trang.'),
 'vf5': ('SUV điện', 'SUV điện cỡ nhỏ, đi được khoảng 300 km mỗi lần sạc. Rộng hơn VF3 và tăng tốc nhanh ngay từ khi xuất phát.'),
 'soluto': ('Sedan', 'Sedan 1.4L đơn giản và tiết kiệm — lựa chọn chạy xăng rẻ nhất trong đội xe. Phù hợp cho hai người, ít hành lý.'),
 'mazda3': ('Sedan', 'Sedan nhỏ gọn với hệ thống treo chắc chắn đặc trưng của Mazda và vô lăng chính xác — lái xe dọc bờ biển thật thú vị.'),
 'rush': ('SUV 7 chỗ', 'SUV 7 chỗ nhỏ gọn, gầm cao — vững vàng hơn trên đường xấu, đủ chỗ cho cả nhóm và hành lý.'),
 'xpander': ('MPV 7 chỗ', 'Mẫu MPV gia đình phổ biến nhất Việt Nam — hàng ghế thứ ba đủ cho người lớn, cốp rộng rãi cho vali.'),
 'veloz': ('MPV 7 chỗ', 'Cùng phân khúc và mức giá với Xpander — dành cho nhóm đông và nhiều hành lý, với độ bền của Toyota.'),
 'creta': ('SUV', 'SUV nhỏ gọn với các tính năng hỗ trợ lái hiện đại và tư thế ngồi cao — thoải mái cho những chuyến đi Đà Lạt.'),
 'xforce': ('SUV, 2024', 'Một trong những mẫu SUV mới nhất trong đội xe — đèn sắc nét, nền tảng mới, thực dụng như Creta.'),
 'luxa': ('Sedan hạng sang', 'Sedan cao cấp của VinFast trên nền tảng BMW 5 Series — động cơ 2.0 turbo, nội thất hạng thương gia. Lựa chọn tốt nhất để đón tiễn sân bay Cam Ranh.'),
 'carnival': ('MPV, 7–11 chỗ', 'MPV gia đình cỡ lớn cho nhóm đến 11 người: khoang rộng, cửa trượt và nhiều chỗ để vali. Tiện cho đưa đón sân bay Cam Ranh và du lịch cả gia đình.'),
}
